# Generated by Django 4.2.1 on 2023-06-02 21:35

import django.core.validators
from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='tile', max_length=225, verbose_name='title')),
                ('description', models.TextField(help_text='Description')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=videos.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=videos.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
            },
        ),
        migrations.CreateModel(
            name='SermonShorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='tile', max_length=225, verbose_name='title')),
                ('description', models.TextField(help_text='Description')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=videos.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=videos.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name': 'Short Sermons',
                'verbose_name_plural': 'Short Sermons',
            },
        ),
    ]
