# Generated by Django 4.2.1 on 2023-06-02 21:35

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='tile', max_length=225, verbose_name='title')),
                ('prologue', models.TextField(help_text='Prologue')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('secondImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('thirdImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('fourthImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=books.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='tile', max_length=225, verbose_name='title')),
                ('prologue', models.TextField(help_text='Prologue')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('secondImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('thirdImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('fourthImage', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=books.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=books.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name': 'Merchandise',
                'verbose_name_plural': 'Merchandise',
            },
        ),
    ]
